/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_calculadora;

import java.util.HashSet;
import java.util.Set;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class Programa extends javax.swing.JFrame {

    public String visor = "";
    public String visorResult = "";
    public String num1Txt = "";
    public String num2Txt = "";
    public String op = "";
    public int num1 = 0;
    public int num2 = 0;
    public int result = 0;
    boolean digitandoPrimeiroNumero = true;

    // Action Listener (ação para todos os botões)
    ActionListener digitarNumeros = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton botao = (JButton) e.getSource();
            String digito = botao.getText();

            if (digitandoPrimeiroNumero) {
                if (num1Txt.length() < 3) {
                    num1Txt += digito;
                    num1 = Integer.parseInt(num1Txt);
                    Display.setText(num1Txt);
                }
            } else if (num2Txt.length() < 3) {
                num2Txt += digito;
                num2 = Integer.parseInt(num2Txt);
                Display.setText(num1Txt + " " + op + " " + num2Txt);
                mostrarResultado();
            }

        }
    };

    void mostrarResultado() {
        try {
            // Verificar se há valores válidos
            if (!num2Txt.isEmpty() && !num1Txt.isEmpty()) {
                if (op.equals("/") && num2 == 0) {
                    DisplayResult.setText("= indefinido");
                    return;
                }

                // Usar operações seguras para detectar overflow
                int resultado = 0;
                switch (op) {
                    case "+" -> {
                        resultado = Math.addExact(num1, num2);
                    }
                    case "-" -> {
                        resultado = Math.subtractExact(num1, num2);
                    }
                    case "*" -> {
                        resultado = Math.multiplyExact(num1, num2);
                    }
                    case "/" -> {
                        if (num2 != 0) {
                            resultado = num1 / num2;
                        }
                    }
                }

                result = resultado;
                DisplayResult.setText("= " + Integer.toString(result));
            }
        } catch (ArithmeticException ex) {
            // Tratar overflow
            DisplayResult.setText("= Overflow");
            System.out.println("Overflow detectado: " + ex.getMessage());
        }
    }

    ActionListener digitarOp = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton botao = (JButton) e.getSource();
            op = botao.getText();
            digitandoPrimeiroNumero = false;
            if (num2Txt.equals("")) {
                Display.setText(num1Txt + " " + op);
            } else {
                Display.setText(num1Txt + " " + op + " " + num2Txt);
                mostrarResultado();
            }
        }
    };

    public Programa() {

        initComponents();
        JButton[] botoesNumericos = {
            Butt0, Butt1, Butt2, Butt3, Butt4,
            Butt5, Butt6, Butt7, Butt8, Butt9
        };

        for (JButton botao : botoesNumericos) {
            botao.addActionListener(digitarNumeros);
        }

        JButton[] botoesOp = {
            ButtMais, ButtMenos, ButtMult, ButtDiv
        };
        for (JButton botao : botoesOp) {
            botao.addActionListener(digitarOp);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCalc = new javax.swing.JPanel();
        PainelDisplay = new javax.swing.JPanel();
        Display = new javax.swing.JLabel();
        DisplayResult = new javax.swing.JLabel();
        PainelButt = new javax.swing.JPanel();
        Butt2 = new javax.swing.JButton();
        ButtVirgula = new javax.swing.JButton();
        ButtClear = new javax.swing.JButton();
        Butt3 = new javax.swing.JButton();
        Butt7 = new javax.swing.JButton();
        ButtMais = new javax.swing.JButton();
        ButtDiv = new javax.swing.JButton();
        Butt5 = new javax.swing.JButton();
        Butt0 = new javax.swing.JButton();
        Butt6 = new javax.swing.JButton();
        Butt1 = new javax.swing.JButton();
        ButtMenos = new javax.swing.JButton();
        Butt4 = new javax.swing.JButton();
        ButtIgual = new javax.swing.JButton();
        Butt8 = new javax.swing.JButton();
        Backspace = new javax.swing.JButton();
        Butt9 = new javax.swing.JButton();
        ButtMult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PainelCalc.setBackground(new java.awt.Color(102, 102, 102));

        PainelDisplay.setBackground(new java.awt.Color(51, 51, 51));
        PainelDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Display.setBackground(new java.awt.Color(0, 0, 0));
        Display.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Display.setForeground(new java.awt.Color(51, 255, 51));
        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Display.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Display.setName(""); // NOI18N

        DisplayResult.setBackground(new java.awt.Color(0, 0, 0));
        DisplayResult.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DisplayResult.setForeground(new java.awt.Color(51, 255, 51));
        DisplayResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DisplayResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DisplayResult.setName(""); // NOI18N

        javax.swing.GroupLayout PainelDisplayLayout = new javax.swing.GroupLayout(PainelDisplay);
        PainelDisplay.setLayout(PainelDisplayLayout);
        PainelDisplayLayout.setHorizontalGroup(
            PainelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDisplayLayout.createSequentialGroup()
                        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDisplayLayout.createSequentialGroup()
                        .addComponent(DisplayResult, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PainelDisplayLayout.setVerticalGroup(
            PainelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDisplayLayout.createSequentialGroup()
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DisplayResult, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelButt.setBackground(new java.awt.Color(51, 51, 51));
        PainelButt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Butt2.setBackground(new java.awt.Color(102, 102, 102));
        Butt2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt2.setText("2");
        Butt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Butt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt2ActionPerformed(evt);
            }
        });

        ButtVirgula.setBackground(new java.awt.Color(102, 102, 102));
        ButtVirgula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtVirgula.setText(",");
        ButtVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtVirgulaActionPerformed(evt);
            }
        });

        ButtClear.setBackground(new java.awt.Color(102, 102, 102));
        ButtClear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtClear.setText("AC");
        ButtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtClearActionPerformed(evt);
            }
        });

        Butt3.setBackground(new java.awt.Color(102, 102, 102));
        Butt3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt3.setText("3");
        Butt3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Butt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt3ActionPerformed(evt);
            }
        });

        Butt7.setBackground(new java.awt.Color(102, 102, 102));
        Butt7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt7.setText("7");
        Butt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt7ActionPerformed(evt);
            }
        });

        ButtMais.setBackground(new java.awt.Color(102, 102, 102));
        ButtMais.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtMais.setText("+");
        ButtMais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtMaisActionPerformed(evt);
            }
        });

        ButtDiv.setBackground(new java.awt.Color(102, 102, 102));
        ButtDiv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtDiv.setText("/");
        ButtDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtDivActionPerformed(evt);
            }
        });

        Butt5.setBackground(new java.awt.Color(102, 102, 102));
        Butt5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt5.setText("5");
        Butt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt5ActionPerformed(evt);
            }
        });

        Butt0.setBackground(new java.awt.Color(102, 102, 102));
        Butt0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt0.setText("0");
        Butt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt0ActionPerformed(evt);
            }
        });

        Butt6.setBackground(new java.awt.Color(102, 102, 102));
        Butt6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt6.setText("6");
        Butt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt6ActionPerformed(evt);
            }
        });

        Butt1.setBackground(new java.awt.Color(102, 102, 102));
        Butt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt1.setText("1");
        Butt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Butt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt1ActionPerformed(evt);
            }
        });

        ButtMenos.setBackground(new java.awt.Color(102, 102, 102));
        ButtMenos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtMenos.setText("-");
        ButtMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtMenosActionPerformed(evt);
            }
        });

        Butt4.setBackground(new java.awt.Color(102, 102, 102));
        Butt4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt4.setText("4");
        Butt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt4ActionPerformed(evt);
            }
        });

        ButtIgual.setBackground(new java.awt.Color(0, 153, 0));
        ButtIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtIgual.setForeground(new java.awt.Color(255, 255, 255));
        ButtIgual.setText("=");
        ButtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtIgualActionPerformed(evt);
            }
        });

        Butt8.setBackground(new java.awt.Color(102, 102, 102));
        Butt8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt8.setText("8");
        Butt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt8ActionPerformed(evt);
            }
        });

        Backspace.setBackground(new java.awt.Color(102, 102, 102));
        Backspace.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Backspace.setText("Backspace");
        Backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceActionPerformed(evt);
            }
        });

        Butt9.setBackground(new java.awt.Color(102, 102, 102));
        Butt9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Butt9.setText("9");
        Butt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt9ActionPerformed(evt);
            }
        });

        ButtMult.setBackground(new java.awt.Color(102, 102, 102));
        ButtMult.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ButtMult.setText("*");
        ButtMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtMultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelButtLayout = new javax.swing.GroupLayout(PainelButt);
        PainelButt.setLayout(PainelButtLayout);
        PainelButtLayout.setHorizontalGroup(
            PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelButtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelButtLayout.createSequentialGroup()
                            .addComponent(Butt7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(Butt8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(Butt9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(ButtMult, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelButtLayout.createSequentialGroup()
                            .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(PainelButtLayout.createSequentialGroup()
                                    .addComponent(Butt0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(ButtVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ButtIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelButtLayout.createSequentialGroup()
                                    .addComponent(ButtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(ButtDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PainelButtLayout.createSequentialGroup()
                        .addComponent(Butt4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(Butt5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(Butt6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ButtMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelButtLayout.createSequentialGroup()
                        .addComponent(Butt1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(Butt2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(Butt3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ButtMais, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelButtLayout.setVerticalGroup(
            PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelButtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butt1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtMais, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butt4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butt7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Butt9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtMult, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butt0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PainelButtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelCalcLayout = new javax.swing.GroupLayout(PainelCalc);
        PainelCalc.setLayout(PainelCalcLayout);
        PainelCalcLayout.setHorizontalGroup(
            PainelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCalcLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PainelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCalcLayout.setVerticalGroup(
            PainelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCalcLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PainelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(PainelButt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt1ActionPerformed

    }//GEN-LAST:event_Butt1ActionPerformed

    private void Butt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt2ActionPerformed

    private void Butt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt3ActionPerformed

    private void ButtMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtMaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtMaisActionPerformed

    private void Butt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt5ActionPerformed

    private void Butt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt6ActionPerformed

    private void ButtMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtMenosActionPerformed

    private void Butt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt4ActionPerformed

    private void Butt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt8ActionPerformed

    private void Butt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt9ActionPerformed

    private void ButtMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtMultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtMultActionPerformed

    private void ButtVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtVirgulaActionPerformed
        Display.setText("( ͡° ͜ʖ ͡°)");
    }//GEN-LAST:event_ButtVirgulaActionPerformed

    private void ButtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtClearActionPerformed
        num1 = 0;
        num2 = 0;
        result = 0;
        num1Txt = "";
        num2Txt = "";
        op = "";
        DisplayResult.setText("");
        Display.setText("");
        digitandoPrimeiroNumero = true;
    }//GEN-LAST:event_ButtClearActionPerformed

    private void Butt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt7ActionPerformed

    private void ButtDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtDivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtDivActionPerformed

    private void Butt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Butt0ActionPerformed

    private void ButtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtIgualActionPerformed
        if (!(DisplayResult.getText().equals("") || DisplayResult.getText().equals("= indefinido"))) {
            System.out.println(result);
            num1 = result;
            num2 = 0;
            num1Txt = Integer.toString(result);
            num2Txt = "";
            op = "";
            DisplayResult.setText("");
            Display.setText(num1Txt);
            digitandoPrimeiroNumero = true;
        }
    }//GEN-LAST:event_ButtIgualActionPerformed

    private void BackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceActionPerformed
        if (digitandoPrimeiroNumero) {
            if (num1Txt.length() > 0) {
                num1Txt = num1Txt.substring(0, num1Txt.length() - 1);
                try {
                    num1 = Integer.parseInt(num1Txt);
                }
                catch (NumberFormatException ex) {
                    num1 = 0;
                    num1Txt = "";
                }
                Display.setText(num1Txt);
            }
        } else {
            if (num2Txt.length() > 0) {
                num2Txt = num2Txt.substring(0, num2Txt.length() - 1);
                if (num2Txt.length() == 0) {
                    result = 0;
                    DisplayResult.setText("");
                    Display.setText(num1Txt + " " + op + " ");
                } else {
                    Display.setText(num1Txt + " " + op + " " + num2Txt);
                    num2 = Integer.parseInt(num2Txt);
                    mostrarResultado();
                }
            } else {
                op = "";
                digitandoPrimeiroNumero = true;
                Display.setText(num1Txt);
            }
        }
    }//GEN-LAST:event_BackspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //PainelDisplay.setResizable(false);
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backspace;
    private javax.swing.JButton Butt0;
    private javax.swing.JButton Butt1;
    private javax.swing.JButton Butt2;
    private javax.swing.JButton Butt3;
    private javax.swing.JButton Butt4;
    private javax.swing.JButton Butt5;
    private javax.swing.JButton Butt6;
    private javax.swing.JButton Butt7;
    private javax.swing.JButton Butt8;
    private javax.swing.JButton Butt9;
    private javax.swing.JButton ButtClear;
    private javax.swing.JButton ButtDiv;
    private javax.swing.JButton ButtIgual;
    private javax.swing.JButton ButtMais;
    private javax.swing.JButton ButtMenos;
    private javax.swing.JButton ButtMult;
    private javax.swing.JButton ButtVirgula;
    private javax.swing.JLabel Display;
    private javax.swing.JLabel DisplayResult;
    private javax.swing.JPanel PainelButt;
    private javax.swing.JPanel PainelCalc;
    private javax.swing.JPanel PainelDisplay;
    // End of variables declaration//GEN-END:variables
}
